spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
  default-produces-media-type: application/json
