spring:
  datasource:
    url: jdbc:h2:file:./data/bookshop_db
    username: s24377
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: h2

section:
  default-number-of-subsections: 5
